title: Smile
author: Kelsey Niemeyer
email: brightnbubbly@github.com
description: > # this means to ignore newlines until "baseurl:"
  Happy. Nerdy. Klutzy. Helpful. Loves animals and food (there is no overlap). Knits. Plays Guitar. Snowboards.
theme: minima

# social links
twitter_username: brightnbubbly16 # DO NOT include the @ character, or else the build will fail!
github_username:  brightnbubbly # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
